### ISSUE TITLE
Does it work with latest bzr?

### ISSUE THREAD

**Issue by khurshid-alam** [jelmer/bzr-rewrite#1]
Does it work with latest bzr (> 2.7?) ?

**Comment by jelmer** [comment]
It'll probably work with Bazaar 2.7; I don't think there have been any API breakages.

**Comment by khurshid-alam** [comment]
@jelmer 

Can you provide a deb? or compile for 18.04 in a PPA? Version 2.6.x has `bzr (<< 2.7~), bzr (>= 2.5~),` in debian/control. So that's why it doesn't compile for me on 18.04.

Thanks.

**Comment by jelmer** [comment]
Sorry, we stopped producing debs for bzr-rewrite. You should be able to install from lp:bzr-rewrite trunk by running:

    bzr branch lp:bzr-rewrite ~/.bazaar/plugins/rewrite

I'm hoping to provide built-in support for rebasing in Breezy (www.breezy-vcs.org), and am not planning further work on bzr-rewrite.

**Comment by jelmer** [comment]
I'm hoping to provide built-in support for rebasing in Breezy (www.breezy-vcs.org), and am not planning further work on bzr-rebase.
